-- =============================================================
--  HIStore'y - Sample Product Images Insert
-- =============================================================
USE `hstore_db`;

INSERT INTO `product_images` (`id`, `product_id`, `file_path`, `is_primary`) VALUES
(1, 1, 'uploads/products/1/thriller_vinyl_front.jpg', 1),
(2, 1, 'uploads/products/1/thriller_vinyl_back.jpg', 0),
(3, 2, 'uploads/products/2/bad_japan_cd_front.jpg', 1),
(4, 2, 'uploads/products/2/bad_japan_cd_obi.jpg', 0),
(5, 3, 'uploads/products/3/history_cd_case.jpg', 1),
(6, 3, 'uploads/products/3/history_cd_discs.jpg', 0),
(7, 4, 'uploads/products/4/dangerous_vinyl_front.jpg', 1),
(8, 5, 'uploads/products/5/off_the_wall_vinyl.jpg', 1),
(9, 6, 'uploads/products/6/thriller_jacket_front.jpg', 1),
(10, 6, 'uploads/products/6/thriller_jacket_back.jpg', 0),
(11, 6, 'uploads/products/6/thriller_jacket_detail.jpg', 0),
(12, 7, 'uploads/products/7/bad_tour_tshirt_front.jpg', 1),
(13, 7, 'uploads/products/7/bad_tour_tshirt_back.jpg', 0),
(14, 8, 'uploads/products/8/sequined_glove_main.jpg', 1),
(15, 8, 'uploads/products/8/sequined_glove_box.jpg', 0),
(16, 9, 'uploads/products/9/history_hoodie.jpg', 1),
(17, 10, 'uploads/products/10/dangerous_cap.jpg', 1),
(18, 11, 'uploads/products/11/bad_tour_programme_signed.jpg', 1),
(19, 11, 'uploads/products/11/bad_tour_programme_coa.jpg', 0),
(20, 12, 'uploads/products/12/thriller_40th_box_open.jpg', 1),
(21, 12, 'uploads/products/12/thriller_40th_box_closed.jpg', 0),
(22, 12, 'uploads/products/12/thriller_40th_contents.jpg', 0),
(23, 13, 'uploads/products/13/funko_pop_thriller.jpg', 1),
(24, 14, 'uploads/products/14/coin_set_display.jpg', 1),
(25, 14, 'uploads/products/14/coin_set_box.jpg', 0),
(26, 15, 'uploads/products/15/neverland_snow_globe.jpg', 1),
(27, 16, 'uploads/products/16/thriller_poster_full.jpg', 1),
(28, 17, 'uploads/products/17/bad_era_photo_print.jpg', 1),
(29, 18, 'uploads/products/18/moonwalker_jp_poster.jpg', 1),
(30, 19, 'uploads/products/19/moonwalker_vhs.jpg', 1),
(31, 20, 'uploads/products/20/this_is_it_dvd.jpg', 1),
(32, 20, 'uploads/products/20/this_is_it_dvd_discs.jpg', 0),
(33, 21, 'uploads/products/21/number_ones_dvd.jpg', 1),
(34, 22, 'uploads/products/22/thriller_3d_bluray.jpg', 1),
(35, 23, 'uploads/products/23/moonwalk_book_cover.jpg', 1),
(36, 23, 'uploads/products/23/moonwalk_book_interior.jpg', 0),
(37, 24, 'uploads/products/24/rolling_stone_2009.jpg', 1),
(38, 25, 'uploads/products/25/magic_madness_book.jpg', 1);
