-- =============================================================
--  HIStore'y - Sample Products Insert
-- =============================================================
USE `hstore_db`;

INSERT INTO `products` (`id`, `name`, `description`, `category`, `price`, `stock`, `condition`, `year`, `is_deleted`) VALUES
(1, 'Thriller Vinyl Record (Original Pressing)', 'Original 1982 US pressing of the best-selling album of all time. Epic Records label. Includes original lyric sleeve. Minor sleeve wear, vinyl plays flawlessly.', 'Albums', 4999.00, 3, 'Good', 1982, 0),
(2, 'Bad Album CD - Limited Japan Edition', 'Japanese market limited edition CD of the 1987 Bad album. Includes OBI strip and bonus track insert. Kept in original jewel case with no cracks.', 'Albums', 2499.00, 5, 'Like New', 1987, 0),
(3, 'HIStory: Past, Present and Future Book I - Double CD', 'Original 1995 double album. Disc 1 is a greatest hits compilation; Disc 2 features new material. Comes in the iconic embossed hardcover case.', 'Albums', 1899.00, 8, 'Good', 1995, 0),
(4, 'Dangerous Album Vinyl (2LP)', 'Original 1991 two-record vinyl set of the Dangerous album. Epic Records. Both records are scratch-free. Gatefold sleeve in very good condition.', 'Albums', 3500.00, 2, 'Good', 1991, 0),
(5, 'Off the Wall Original Vinyl Record', 'The album that launched Michael Jackson as a solo superstar. Original 1979 Epic Records US pressing. Light surface marks, plays without skipping.', 'Albums', 2800.00, 4, 'Fair', 1979, 0),
(6, 'Thriller Era Red Leather Jacket Replica', 'High-quality replica of the iconic red and black leather jacket worn in the Thriller music video. Premium PU leather, full lining, silver zipper hardware. Sizes S to 3XL available.', 'Apparel', 3200.00, 15, 'New', 1983, 0),
(7, 'Bad Tour 1987 Concert T-Shirt (Original)', 'Authentic vintage concert tee from the 1987 Bad World Tour. Front features tour artwork; back lists all tour dates. Light fading consistent with age.', 'Apparel', 1500.00, 6, 'Fair', 1987, 0),
(8, 'Michael Jackson Sequined Glove Replica', 'Hand-crafted replica of the iconic white rhinestone glove. Over 1,000 hand-sewn Swarovski-style crystals. One size fits most. Comes in a velvet display box.', 'Apparel', 1200.00, 20, 'New', 1983, 0),
(9, 'HIStory Tour Crew Hoodie', 'Official HIStory World Tour crew sweatshirt. Black with embroidered front logo and tour branding on the back. Heavy cotton blend. Size: XL.', 'Apparel', 2200.00, 3, 'Good', 1996, 0),
(10, 'Dangerous Tour Souvenir Cap', 'Original black snapback cap from the 1992-1993 Dangerous World Tour. Embroidered Michael Jackson signature on front panel. Adjustable strap.', 'Apparel', 950.00, 7, 'Good', 1992, 0),
(11, 'Michael Jackson Signed Tour Programme (Bad Tour)', 'Official Bad Tour programme signed in black marker by Michael Jackson. Signature authenticated with holographic COA sticker from JSA. Framed in UV-protective glass.', 'Collectibles', 125000.00, 1, 'Good', 1987, 0),
(12, 'Thriller 40th Anniversary Limited Edition Box Set', 'Limited to 10,000 units worldwide. Contains remastered CD, 7-inch single, 60-page hardcover book, replica concert ticket, and commemorative enamel pin.', 'Collectibles', 5800.00, 10, 'New', 2022, 0),
(13, 'MJ Funko Pop Figure - Thriller Edition', 'Official licensed Funko Pop vinyl figure of Michael Jackson in the Thriller red leather jacket. In original window box. Figure #26 from the Rocks! series.', 'Collectibles', 750.00, 25, 'New', 2011, 0),
(14, 'Michael Jackson Bronze Commemorative Coin Set', 'Set of 3 bronze-plated commemorative coins. Each coin features a different era: Off the Wall, Thriller, and HIStory. Presented in a velvet-lined wooden box.', 'Collectibles', 2100.00, 12, 'New', 2010, 0),
(15, 'Neverland Ranch Snow Globe', 'Collectible snow globe featuring a miniature replica of the Neverland Ranch main house. Wind-up music box base plays "Ben". Limited edition of 500 pieces.', 'Collectibles', 3800.00, 4, 'Like New', 2005, 0),
(16, 'Thriller Original Movie Poster (27x41)', 'Original US one-sheet promotional poster for the Thriller short film. 27 x 41 inches. Professionally linen-backed for preservation. Unfolded, stored flat.', 'Posters', 8500.00, 2, 'Good', 1983, 0),
(17, 'Bad Era Promotional Photo Print - Signed Reprint', 'High-quality 11x14 inch archival print from the 1987 Bad promotional photoshoot. Printed on 300gsm matte fine-art paper. Unframed.', 'Posters', 650.00, 30, 'New', 1987, 0),
(18, 'Moonwalker Film Japanese Promo Poster', 'Rare Japanese B2-size (28x20 inch) promotional poster for the 1988 film Moonwalker. Minor edge wear. Never folded.', 'Posters', 4200.00, 1, 'Good', 1988, 0),
(19, 'Moonwalker VHS Tape (Original US Release)', 'Original 1988 US VHS release of the Moonwalker film. Epic Music Video label. Tape plays perfectly. Clamshell case has light shelf wear.', 'Music', 799.00, 5, 'Good', 1988, 0),
(20, 'This Is It Concert Film DVD (Collector Edition)', 'Two-disc collector edition DVD of the 2009 This Is It concert documentary. Includes bonus footage, behind-the-scenes material, and photo booklet. Sealed.', 'Music', 899.00, 18, 'New', 2009, 0),
(21, 'Michael Jackson: Number Ones DVD', 'Official DVD compilation featuring music videos for 18 number-one hits. Region 0 (plays worldwide). Includes Making Of documentary for selected videos.', 'Music', 599.00, 14, 'New', 2003, 0),
(22, 'Thriller 3D Blu-ray Disc', 'The landmark short film remastered in stunning 3D and 4K resolution. Directed by John Landis. Includes original 2D version and director commentary track.', 'Music', 1100.00, 9, 'New', 2017, 0),
(23, 'Moonwalk Autobiography - First Edition Hardcover', 'First edition hardcover of Michael Jackson\'s 1988 autobiography Moonwalk. Published by Doubleday. Dust jacket intact with minor edge wear. Interior pages crisp.', 'Merchandise', 3500.00, 3, 'Good', 1988, 0),
(24, 'Rolling Stone Magazine - MJ Tribute Issue (2009)', 'Special double-issue tribute edition of Rolling Stone Magazine following Michael Jackson\'s passing. July 2009. Unread. Stored flat in a protective sleeve.', 'Merchandise', 850.00, 6, 'Like New', 2009, 0),
(25, 'The Magic and the Madness Biography by J. Randy Taraborrelli', 'Updated 2003 edition of the acclaimed Michael Jackson biography. Hardcover. 706 pages. No writing or highlighting. Minor spine crease.', 'Merchandise', 780.00, 8, 'Good', 2003, 0);