const express = require('express')
const router = express.Router()
const { checkAdmin, verifyToken } = require('../middlewares/auth')
const productController = require('../controllers/productController')
const upload = require('../utils/multer')

router.get('/products', productController.listProducts)
router.get('/products/:id', productController.getProduct)
router.get('/products/:id/reviews', productController.listProductReviews)
router.post('/products/:id/reviews', verifyToken, productController.createProductReview)
router.post('/products', verifyToken, checkAdmin, productController.createProduct)
router.put('/products/:id', verifyToken, checkAdmin, productController.updateProduct)
router.delete('/products/:id', verifyToken, checkAdmin, productController.deleteProduct)
router.patch('/products/:id/deactivate', verifyToken, checkAdmin, productController.deactivateProduct)
router.patch('/products/:id/reactivate', verifyToken, checkAdmin, productController.reactivateProduct)
router.post('/products/:id/images', verifyToken, checkAdmin, upload.array('images', 10), productController.uploadImages)
router.delete('/products/:id/images/:imageId', verifyToken, checkAdmin, productController.deleteImage)
router.patch('/products/:id/images/:imageId/primary', verifyToken, checkAdmin, productController.setPrimaryImage)

module.exports = router